# Generated by Django 3.2.7 on 2021-10-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
